apiVersion: v2
name: chart-imagem
description: meu primeiro chart
type: application
version: 0.1.0
appVersion: "1.16.0"
icons: https://png.pngtree.com/png-clipart/20190117/ourmid/pngtree-hand-painted-love-tooth-day-tooth-rose-teeth-png-image_434611.jpg